name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies for simple-mind-map
        run: |
          cd simple-mind-map
          npm install --legacy-peer-deps
          npm run build
          cd ..

      - name: Install Dependencies for web
        run: |
          cd web
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/dist
          branch: gh-pages